version: "3.11"
services:
    web:
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/school
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - POSTGRES_DB=aulas
            - POSTGRES_USER=icaro
            - POSTGRES_PASSWORD=123123123
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432

    db:
        image: postgres
        environment:
            POSTGRES_DB: aulas
            POSTGRES_USER: icaro
            POSTGRES_PASSWORD: 123123123
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
