# Generated by Django 4.1.7 on 2023-02-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=15)),
                ('nome_curso', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('1', 'Iniciante'), ('2', 'Básico'), ('3', 'Intermediário'), ('4', 'Avançado'), ('5', 'Avançado+')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('codigo_matricula', models.CharField(max_length=12)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
